### ISSUE TITLE
Upload and Gallery options bug ?

### ISSUE THREAD

**Issue by HiepVu511** [gambitph/Titan-Framework#317]
Hi guys,

I tried to create 'Gallery' option but there was this error: 
```Titan Framework Error: Option type or extended class gallery does not exist.
Array
(
    [type] => gallery
    [name] => My Gallery Option
    [id] => my_gallery_option
    [hidden] => 
)```

Then i created a 'Upload' option but all image i uploaded always cropped to 150 x 150 px 

I'm using Wordpress 4.4.1 and Titan Framework 1.9.2

**Comment by SiamKreative** [comment]
Despite the fact the documentation is still out there, I just found out it has been removed: https://github.com/gambitph/Titan-Framework/commit/bd23623 since version 1.8.1.

**Comment by Crownie** [comment]
Hi TuiLaHiep, what code were you using to get the image from the frontend?

**Comment by oherman** [comment]
Gallery is being redone right now. Sorry about it, but hopefully this should be sorted out soon.

**Comment by konzalala** [comment]
I have a same problem.

**Comment by ReggieDuran** [comment]
We've fixed it and we've implemented it again. acb2db2d43911c5efa743f33beb624c957af7047

**Comment by ganmahmud** [comment]
@ReggieDuran The bug still exists with the latest version. Could you please confirm ?

**Comment by ReggieDuran** [comment]
@ganmahmud same bug in this issue?
